name = "realtime"
main = "worker/index.js"
compatibility_date = "2023-06-17"
workers_dev = false

[env.integration-testing]
name = "realtime-integration-testing"
route = { pattern = "realtime-integration-testing.dekanat.pp.ua", custom_domain = true, zone_name = "dekanat.pp.ua" }

[env.prod]
name = "realtime"
route = { pattern = "realtime.dekanat.pp.ua", custom_domain = true, zone_name = "dekanat.pp.ua" }
