name = "realtime"
main = "worker/index.js"
compatibility_date = "2023-06-17"
workers_dev = false

[site]
  bucket = "./public/{ENV}"

[env.test]
name = "realtime-test"
route = { pattern = "realtime-test.dekanat.pp.ua", custom_domain = true, zone_name = "dekanat.pp.ua" }

[env.production]
name = "realtime"
route = { pattern = "realtime.dekanat.pp.ua", custom_domain = true, zone_name = "dekanat.pp.ua" }
