name: Deploy to Cloudflare and AWS

on:
  push:
    branches: ['main']

jobs:
  test:
    name: Test and build node
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.environments.outputs.ENVIRONMENTS }}
    steps:
       - uses: actions/checkout@v3
       - name: Use Node.js 18.x
         uses: actions/setup-node@v3
         with:
           node-version: 18.x

       - name: Cache dependencies
         uses: actions/cache@v3
         with:
           path: ~/.npm
           key: npm-${{ hashFiles('package-lock.json') }}
           restore-keys: npm-

       - name: Install node packages
         run: npm ci --no-audit

       - name: Run tests
         run: npm test

       - id: environments
         name: Get environments list
         run: echo "ENVIRONMENTS=$(./get-environments.js)" >> $GITHUB_OUTPUT

  deploy-assets:
    name: Deploy assets to Cloudflare pages
    runs-on: ubuntu-latest
    needs: test
    outputs:
      cloudflare_zones: ${{ steps.cloudflare_zones.outputs.ZONES }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install node packages
        run: npm ci --no-audit

      - name: Build public
        run: ./build-public.js

      - name: Deploy assets to cloudflare
        run: |
          npx wrangler pages deploy public/ --project-name=${{ vars.CLOUDFLARE_ASSETS_PROJECT}}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - id: cloudflare_zones
        name: extract cloudflare zone
        run: echo "ZONES=$(./extract_cloudflare_zone.js)" >> $GITHUB_OUTPUT

  purge-cloudflare-cache:
    runs-on: ubuntu-latest
    needs: deploy-assets
    strategy:
      matrix:
        cloudflare_zone: ${{fromJson(needs.deploy-assets.outputs.cloudflare_zones)}}
    steps:
      - name: Purge Cloudflare Pages Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ZONE: ${{ matrix.cloudflare_zone }}


  deploy-cloudflare-worker:
    name: Deploy to AWS and Cloudflare workers
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: ${{fromJson(needs.test.outputs.environments)}}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install node packages
        run: npm ci --omit=dev --no-audit

      - name: serverless deploy
        run: npx serverless deploy --stage ${{ matrix.env }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Put AWS credentials as Cloudflare Workers vars in wrangler.toml
        run: |
          echo -e "\n[env.${{ matrix.env }}.vars]" >> wrangler.toml
          grep -v ServerlessDeploymentBucketName vars-${{ matrix.env }}.toml >> wrangler.toml
          rm vars-${{ matrix.env }}.toml

      - name: Get AWS Secret for put into wrangler
        id: aws_secret
        run: |
          PRODUCER=$(aws ssm get-parameter --name /realtime-changes-${{ matrix.env }}-producer/secret --output text --query Parameter.Value)
          echo "::add-mask::$PRODUCER"
          echo "PRODUCER=$PRODUCER" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy cloudflare workers
        run: |
          echo ${{ steps.aws_secret.outputs.PRODUCER }} | npx wrangler secret put AwsSecretAccessKey --env ${{ matrix.env }}
          npx wrangler deploy  --env ${{ matrix.env }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
